import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Case = { id:string; outcome:string; transaction_count:number };
type Detail = { id:string; outcome:string; transaction_count:number; uncertainty:string; rationale:string };
type Txn = { id:string; timestamp:string; from:string; to:string; amount:number; currency:string; rail:string };
type Provenance = { provider:string; dataset:string; version:number; retrieved:string; license:string; source_sha256:string; slice_sha256:string; selection:string; label:string };
const api = <T,>(path:string) => fetch(`/api${path}`).then(r => r.ok ? r.json() as Promise<T> : Promise.reject(new Error("Unable to load the bounded public casefile.")));

function App() {
  const [cases, setCases] = useState<Case[]>([]); const [active, setActive] = useState<Case | null>(null); const [detail, setDetail] = useState<Detail | null>(null); const [timeline, setTimeline] = useState<Txn[]>([]); const [provenance, setProvenance] = useState<Provenance | null>(null); const [rationale, setRationale] = useState(""); const [decision, setDecision] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api<{items:Case[]}>("/cases"), api<Provenance>("/provenance")]).then(([c,p]) => { setCases(c.items); setActive(c.items[0]); setProvenance(p); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (!active) return; Promise.all([api<Detail>(`/cases/${active.id}`), api<{items:Txn[]}>(`/cases/${active.id}/timeline?limit=18`)]).then(([d,t]) => { setDetail(d); setTimeline(t.items); setDecision(""); setRationale(""); }).catch(e => setError(e.message)); }, [active]);
  if (error) return <main className="state"><h1>Casefile unavailable.</h1><p>{error}</p><button onClick={() => location.reload()}>Retry</button></main>;
  return <main><header className="masthead"><div><p className="stamp">PUBLIC · REALISTIC SYNTHETIC BANKING DATA</p><h1>Signal Ledger</h1></div><p>Precomputed research context · no live feed · no visitor inference</p></header><section className="opening"><div><p className="lede">A bounded transaction-monitoring research workbench for the human decision after the rank.</p><p className="disclaimer">Two simulated cases: inspect time, payments, and counterparties; then record a browser-only rationale. Neither outcome is a compliance recommendation, accusation, or production decision.</p></div><aside><span>Decision flow</span><strong>timeline → topology → context → human record</strong><small>Analyst capacity and false-positive cost stay visible.</small></aside></section><div className="workbench"><nav className="queue" aria-label="Guided simulated cases"><div className="section-line"><span>Guided cases</span><b>2 time-bound paths</b></div>{cases.map(item => <button className={`case-row ${active?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setActive(item)}><strong>{item.outcome}</strong><small>{item.transaction_count} bounded transactions</small></button>)}</nav><section className="investigation"><div className="section-line"><span>Timeline playback</span><b>ACH · bounded public slice</b></div><ol className="timeline">{timeline.map(item => <li key={item.id}><time>{item.timestamp}</time><span>{item.from} → {item.to}</span><b>{item.amount.toLocaleString(undefined,{maximumFractionDigits:2})} {item.currency}</b><small>{item.rail}</small></li>)}</ol></section><aside className="evidence"><p className="stamp">Simulated case</p><h2>{detail?.outcome ?? "Loading…"}</h2><p>{detail?.uncertainty}</p><h3>Human audit record</h3><label htmlFor="rationale">Analyst rationale</label><textarea id="rationale" value={rationale} onChange={e => setRationale(e.target.value)} placeholder="Record what context changed your view…" /><div className="actions"><button onClick={() => setDecision("Recorded simulated escalation in browser memory only.")}>Simulate escalation</button><button onClick={() => setDecision("Recorded simulated closure in browser memory only.")}>Simulate closure</button></div>{decision && <p className="callout">{decision} {rationale && "Rationale retained until this page is refreshed."}</p>}</aside></div><section className="method"><div><p className="stamp">Provenance & limits</p><h2>Data lineage is evidence.</h2><p>{provenance?.label}. IBM AML-Data v{provenance?.version}; retrieved {provenance?.retrieved}; {provenance?.license}. Slice selection: {provenance?.selection}</p></div><dl><div><dt>Provider</dt><dd>{provenance?.provider}</dd></div><div><dt>Source checksum</dt><dd>{provenance?.source_sha256}</dd></div><div><dt>Slice checksum</dt><dd>{provenance?.slice_sha256}</dd></div><div><dt>Research boundary</dt><dd>Elliptic evaluation remains local-only; public surface makes no benchmark claim.</dd></div></dl></section></main>;
}
createRoot(document.getElementById("root")!).render(<App />);
